language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master
before_script:
  - npm i -g firebase-tools
  - npm i
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
notifications:
  email:
    - on_failure: change
